# Generated by Django 3.2.20 on 2023-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsblog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Books'), (1, 'Lamps'), (2, 'Interior'), (3, 'Other')]),
        ),
    ]
