# Generated by Django 3.2.20 on 2023-09-02 16:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsblog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
        migrations.AddField(
            model_name='post',
            name='listing_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='listing_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='slider_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='slider_image'),
        ),
    ]
