# Generated by Django 3.2.20 on 2023-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsblog', '0005_auto_20230902_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
