# Generated by Django 3.2.20 on 2023-09-10 10:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsblog', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='listing_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slider_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
