# Generated by Django 3.2.20 on 2023-09-10 13:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsblog', '0010_auto_20230910_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='listing_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='listing_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slider_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='slider_image'),
        ),
    ]
